### PR TITLE
Add features into configuration again

### PR DESCRIPTION
**Pull request by rjmackay**
Part of ushahidi/platform#638

Todo:
- [x] Return 'available' or similar from the data provider API so we can handle that in the UI
- [x] Add tests, particularly for access control
- [x] Check my available data provider code actually works
- [x] Don't run disabled data providers (ie. from CLI tasks)

[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/684)

### CODE REVIEW

**Comment by rjmackay** [comment]
Something seems to have gone horribly broken and its trying to write config to a file, not the db.. very confused

**Comment by rjmackay** [comment]
@hollycorbett added some todos, feel free to pick this up again while I sleep. Or just work on update the client to match these changes.

**Comment by rjmackay** [comment]
Once todos on this are done, we can land this. Work for quota based limits (#640) should happen on a follow up diff.

**Comment by willdoran** [comment]
@rjmackay I've added one method for preventing unavailable data providers from being used. This will work for the twitter and email provider as well. However, I wanted to see if it was better instead to prevent the data providers at an earlier point by preventing their registration here:

https://github.com/ushahidi/platform/blob/08d2bcd8a19e469a7d11618f51c20a3da4bb2799/modules/data-provider/classes/DataProvider/Core.php#L100

What do you think? 

If we did do that then we would have to call registration again when the tier is up/down graded, that seems like a simpler option and a more simple control point as the data providers should be agnostic of whether they are available or not.

**Comment by rjmackay** [comment]
@willdoran I don't think we can limit the providers earlier or we wouldn't be able to return disabled/unavailable providers in the API

**Comment by willdoran** [comment]
Ok, cool. That works for me.

**Comment by rjmackay** [comment]
Reviewed 2 of 6 files at r2, 2 of 3 files at r3, 8 of 8 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[application/classes/Ushahidi/Repository/Config.php, line 40 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNHdid3XAkcBmCySl0)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/application/classes/Ushahidi/Repository/Config.php#L40)):</sup>
Why are we loading available features for every config group?
This should only happen with $group = features ...

---

<sup>**[application/classes/Ushahidi/Validator/Config/Update.php, line 105 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNHscoW60ZfL5fJIhz)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/application/classes/Ushahidi/Validator/Config/Update.php#L105)):</sup>
indenting is borked

---

<sup>**[plugins/data-provider-email/classes/DataProvider/Email.php, line 28 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNI9kTBPh48Gtl1TY-)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/plugins/data-provider-email/classes/DataProvider/Email.php#L28)):</sup>
indenting?

---

<sup>**[plugins/data-provider-email/classes/DataProvider/Email.php, line 88 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNI_FGd2-kvfgOKzR-)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/plugins/data-provider-email/classes/DataProvider/Email.php#L88)):</sup>
Is there a way to do a general check before fetch() or send() is even called? Or just move these checks to the parent class, then call parent::fetch() first.

---

<sup>**[plugins/data-provider-email/classes/DataProvider/Email.php, line 90 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNI8VlSb8HgcM9qrrw)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/plugins/data-provider-email/classes/DataProvider/Email.php#L90)):</sup>
indenting?

---

<sup>**[plugins/data-provider-email/classes/DataProvider/Email.php, line 161 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNILb-dejKTJtuyRji)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/plugins/data-provider-email/classes/DataProvider/Email.php#L161)):</sup>
indent 

---

<sup>**[src/Core/Tool/Authorizer/ConfigAuthorizer.php, line 54 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNItFvdZJZI3MxrOnb)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/src/Core/Tool/Authorizer/ConfigAuthorizer.php#L54)):</sup>
did you or I add test for this?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/684)

**Comment by willdoran** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[application/classes/Ushahidi/Repository/Config.php, line 40 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNHdid3XAkcBmCySl0)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/application/classes/Ushahidi/Repository/Config.php#L40)):</sup>
Yep, I've changed this to simply use the features api as you suggested.

---

<sup>**[plugins/data-provider-email/classes/DataProvider/Email.php, line 88 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNI_FGd2-kvfgOKzR-)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/plugins/data-provider-email/classes/DataProvider/Email.php#L88)):</sup>
I think moving these to the parent is probably the most effective. I'll look again to see if I can intercept before fetch and send

---

<sup>**[src/Core/Tool/Authorizer/ConfigAuthorizer.php, line 54 \[r7\]](https://reviewable.io:443/reviews/ushahidi/platform/684#-JzNItFvdZJZI3MxrOnb)** ([raw file](https://github.com/ushahidi/platform/blob/078e9a5390e6c7a90e5d7e62a600deb87a7c7ef7/src/Core/Tool/Authorizer/ConfigAuthorizer.php#L54)):</sup>
I don't think I worked on this file.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/684)

**Comment by rjmackay** [comment]
Looking pretty good. I'd like some tests for the access control on config, ie. to ensure admins can't change their own feature config via the API. But we should land and create a follow up task for that

---

Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/684)

**Pull request merged**
