### PR TITLE
Feature/migration

### PR DESCRIPTION
**Pull request by zhalloran**
This pull request makes the following changes:
- Added migrate, migrate/status. migrate/migrate & migrate/rollback end points to the API (Do we want to have a rollback option?).
- Added Migrate controller class. Calls to this controller throw a 403 error if the user is not an admin.
- Added 'migrate' record to oauth_scopes tables

Test these changes by:
- execute signed api calls to end points
- tests still need to be written

Fixes ushahidi/platform#1003

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform/1066)

### CODE REVIEW

**Comment by rjmackay** [comment]
Not following our typical structure - but I think migration would always be a special case.
Main thing we need to handle is the initial setup: when we have no tables at all.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[application/classes/Controller/Api/Migrate.php, line 27 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1066#-KGxajL8CXw26U9bof-k:-KGxajL8CXw26U9bof-l:-1532934950) ([raw file](https://github.com/ushahidi/platform/blob/631442a55bba2a6e77925a5c2163c1b9cdab388b/application/classes/Controller/Api/Migrate.php#L27)):*
I don't know if it matters here, but in general controller in platform will usually just call out to a usecase, which then handles everything else. 

---

*[application/classes/Controller/Api/Migrate.php, line 30 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1066#-KGxfmHX-p3Wwq53E88G:-KGxfmHX-p3Wwq53E88H:1052805060) ([raw file](https://github.com/ushahidi/platform/blob/631442a55bba2a6e77925a5c2163c1b9cdab388b/application/classes/Controller/Api/Migrate.php#L30)):*
We need handling for a special case where no tables exist at all - in which case oauth checks will fail, as will checking role.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1066#-:-KGxgRBRccwwou8SN3F7:-564140620)*

**Comment by zhalloran** [comment]
Awesome. Thanks for the feedback.

**Comment by zhalloran** [comment]
@rjmackay Broke out migration/migrate into it's own class to allow for unauthenticated requests. Tests are...lacking.

**Comment by rjmackay** [comment]
Added some barebones testing. Landing this thing

**Pull request merged**
