### PR TITLE
Adding Google2fa for platform

### PR DESCRIPTION
**Pull request by willdoran**
This pull request makes the following changes:
- Adds Google 2fa library
- Updates composer lock file
- Adds Generate and Verify usecases for user
- Adds 2fa routes for enable and verify of one time passwords
- Adds test cases for 2fa and for oauth with 2fa flow
- Adds 2fa api
- Adds user_google2fa_secrets table
- Adds user_google_2fa enable field to user table

Test these changes by:
- The 2fa and oauth feature tests should pass

Fixes ushahidi/platform#980

Ping @ushahidi/platform

---

This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform/1002)

### CODE REVIEW

**Comment by rjmackay** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[application/classes/Controller/OAuth.php, line 74 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcSAkt_JF8Djx0Clc-:-KEcSAkuo2Umvf8p-HEv:-332788364) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/classes/Controller/OAuth.php#L74)):*
I see what you mean about it being a bit ugly and tied to the oauth controller.
Is there any way to subclass parts of the oauth lib and push this code into there?

We're a bit out of date on the oauth lib so make sure you hit the right version of the docs ..

---

*[application/classes/Controller/Api/2fa.php, line 17 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcSXssGFlGUi43IQVS:-KEcSXssGFlGUi43IQVT:7287979) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/classes/Controller/Api/2fa.php#L17)):*
I think you've got mixed spaces and tabs everywhere again :/

---

*[application/routes/default.php, line 134 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcTfGaMuenEt2ah_Rf:-KEcTfGaMuenEt2ah_Rg:-1458792308) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/routes/default.php#L134)):*
I think you could add `(<action>)` to this route and it'll cover the verify route below too

---

*[application/tests/datasets/ushahidi/Base.yml, line 66 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcTtFVTwJTri8xtjim:-KEcTtFWCm0FseLNmcCM:1040056935) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/datasets/ushahidi/Base.yml#L66)):*
Do we need to support multiple 2fa secrets per user? or should this just be a column on the user table?

---

*[application/tests/features/api.2fa.feature, line 8 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcU1lWt16fkzeN8CI8:-KEcU1lXZ7ik2rM4OU1_:-1015309688) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/features/api.2fa.feature#L8)):*
why are we posting email address?? don't we have that on the current user anyway. I think this should probably be an empty post request.

---

*[application/tests/features/api.oauth.feature, line 6 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcUCR5VnNh8EkLvYB5:-KEcUCR5VnNh8EkLvYB6:754617144) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/features/api.oauth.feature#L6)):*
If you're going to switch to JSON data - please change the header..

---

*[application/tests/features/api.oauth.feature, line 74 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcUd3s-pfTrJEoaBej:-KEcUd3tspH-k9ItG_wM:-2107475699) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/features/api.oauth.feature#L74)):*
This should probably be called an OTP or token, not a secret - since we've referred to the secret key as the 2fa secret above.

---

*[migrations/20160325000532_add_to_user_google2fa_enabled.php, line 27 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcVG9Gn3P8AvHsE4b8:-KEcVG9HFADrvxWq0YsS:-34360778) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/migrations/20160325000532_add_to_user_google2fa_enabled.php#L27)):*
does this really need to be `null` shouldn't it always be true or false?

---

*[migrations/20160325000532_add_to_user_google2fa_enabled.php, line 28 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcVBe--sTewA8V-62k:-KEcVBe0nQnSpDCKA4-R:-2103146484) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/migrations/20160325000532_add_to_user_google2fa_enabled.php#L28)):*
should the default be `false` or `null`??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002)*

**Comment by willdoran** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[application/classes/Controller/OAuth.php, line 74 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcSAkt_JF8Djx0Clc-:-KEgTGM7CY8RFg_nUkQv:-905539719) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/classes/Controller/OAuth.php#L74)):*
Checking this now.

---

*[application/classes/Controller/Api/2fa.php, line 17 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcSXssGFlGUi43IQVS:-KEgTIbg5aM6Os1F1nNU:-267211881) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/classes/Controller/Api/2fa.php#L17)):*
Argh, yes, sorry - I will go beat vim

---

*[application/routes/default.php, line 134 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcTfGaMuenEt2ah_Rf:-KEgTaRm6yF4doSj6yPq:-1942488315) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/routes/default.php#L134)):*
Excellent, I've combined them.

---

*[application/tests/datasets/ushahidi/Base.yml, line 66 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcTtFVTwJTri8xtjim:-KEgUVFZpTJTf0KFunfn:-629375063) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/datasets/ushahidi/Base.yml#L66)):*
We don't need multiple secrets per user BUT I wanted to avoid having to strip them out when the user is returned. To be certain they would never accidentally be returned. What do you prefer?

---

*[application/tests/features/api.2fa.feature, line 8 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcU1lWt16fkzeN8CI8:-KEgV75YFt6xPlXrsmT7:1590174429) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/features/api.2fa.feature#L8)):*
Yep we do, I'll remove that.

---

*[application/tests/features/api.oauth.feature, line 74 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcUd3s-pfTrJEoaBej:-KEgVjYtrtKihbqoLMVa:257435119) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/application/tests/features/api.oauth.feature#L74)):*
Changed

---

*[migrations/20160325000532_add_to_user_google2fa_enabled.php, line 27 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KEcVG9Gn3P8AvHsE4b8:-KEgW9QfSpHzwE5DKsCf:1024554113) ([raw file](https://github.com/ushahidi/platform/blob/b3389201f5fd1575505eb249a8b529c277ecfdff/migrations/20160325000532_add_to_user_google2fa_enabled.php#L27)):*
No, I'll leave it set to default false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002)*

**Comment by rjmackay** [comment]
Sorry for the late review - picked up a few issues.

---

Reviewed 2 of 7 files at r2, 7 of 8 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[application/classes/Controller/OAuth.php, line 74 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJl1OtcETTAhdl1GXd:-KGJl1OtcETTAhdl1GXe:-623331208) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/OAuth.php#L74)):*
Could we take everything from the if and put it in a function??

Ideally throw an exception if 2fa validation fails - then we can handle that failure in a catch like the others.

---

*[application/classes/Controller/OAuth.php, line 77 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJkm4wDBXIW6j_ymAh:-KGJkm4xezzTSY90Cics:314938897) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/OAuth.php#L77)):*
minor: use `[]` array format

---

*[application/classes/Controller/Api/2fa.php, line 3 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJlS91Cz6k86LanblD:-KGJlS91Cz6k86LanblE:-1229402627) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/Api/2fa.php#L3)):*
does this file still have 2 space indents? it look wrong..

---

*[application/classes/Ushahidi/Repository/User.php, line 182 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJlYjXHZ1yvL08LWqk:-KGJlYjXHZ1yvL08LWql:-136275081) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Ushahidi/Repository/User.php#L182)):*
mixed space + tabs :(

---

*[src/Core/Usecase/User/DisableGoogle2fa.php, line 33 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmQxFJ57EqvqnmhgZ:-KGJmQxFJ57Eqvqnmhg_:456042222) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/DisableGoogle2fa.php#L33)):*
Do we need all these traits still?

---

*[src/Core/Usecase/User/DisableGoogle2fa.php, line 71 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmCxcU3j27Hx0TfDd:-KGJmCxcU3j27Hx0TfDe:805519707) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/DisableGoogle2fa.php#L71)):*
we're not doing an authorizer check here??

---

*[src/Core/Usecase/User/GenerateGoogle2fa.php, line 71 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmTxEV5WDyatP9T8C:-KGJmTxEV5WDyatP9T8D:1806058656) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/GenerateGoogle2fa.php#L71)):*
No authorization?

---

*[src/Core/Usecase/User/GenerateGoogle2fa.php, line 74 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmVf9V0QGvlF4mgBz:-KGJmVf9V0QGvlF4mgC-:1051820954) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/GenerateGoogle2fa.php#L74)):*
mixed tabs + spaces

---

*[src/Core/Usecase/User/VerifyGoogle2fa.php, line 22 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmkIYUSL2Vc65dDo5:-KGJmkIYUSL2Vc65dDo6:1778092133) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/VerifyGoogle2fa.php#L22)):*
Could we reuse this usecase in the oauth controller rather than doing check manually??

---

*[src/Core/Usecase/User/VerifyGoogle2fa.php, line 80 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJms9iS88vBjtlmkcq:-KGJms9iS88vBjtlmkcr:-369430769) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/VerifyGoogle2fa.php#L80)):*
what are we returning if verification fails? should it be an exception? or at least `google2fa_valid => false`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002#-:-KGJn15aVkjjTo2DW6_K:1157406073)*

**Comment by willdoran** [comment]
Review status: 12 of 21 files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[application/classes/Controller/OAuth.php, line 74 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJl1OtcETTAhdl1GXd:-KGSvMj9zQ3Xj7humXY8:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/OAuth.php#L74)):*
Done.

---

*[application/classes/Controller/OAuth.php, line 77 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJkm4wDBXIW6j_ymAh:-KGSk3KHhTF74YH_o9O2:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/OAuth.php#L77)):*
Done.

---

*[application/classes/Controller/Api/2fa.php, line 3 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJlS91Cz6k86LanblD:-KGSjtSTGSb3yJvbIB3c:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Controller/Api/2fa.php#L3)):*
Done.

---

*[application/classes/Ushahidi/Repository/User.php, line 182 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJlYjXHZ1yvL08LWqk:-KGSi6ZhxOaQrVPnRRFY:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/application/classes/Ushahidi/Repository/User.php#L182)):*
Done.

---

*[src/Core/Usecase/User/DisableGoogle2fa.php, line 33 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmQxFJ57EqvqnmhgZ:-KGSDs7p6cKcsnnWsOQ5:1098938198) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/DisableGoogle2fa.php#L33)):*
Yep, I believe so, they are used in api controller and to load the entity.

---

*[src/Core/Usecase/User/DisableGoogle2fa.php, line 71 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmCxcU3j27Hx0TfDd:-KGSvRY51pPFZymKyQ9r:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/DisableGoogle2fa.php#L71)):*
Done.

---

*[src/Core/Usecase/User/GenerateGoogle2fa.php, line 71 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmTxEV5WDyatP9T8C:-KGSvUl2mk6lvi0cwSEQ:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/GenerateGoogle2fa.php#L71)):*
Done.

---

*[src/Core/Usecase/User/GenerateGoogle2fa.php, line 74 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJmVf9V0QGvlF4mgBz:-KGSoK4JKlDnbmWs2Dqp:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/GenerateGoogle2fa.php#L74)):*
Done.

---

*[src/Core/Usecase/User/VerifyGoogle2fa.php, line 80 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGJms9iS88vBjtlmkcq:-KGSwOyEB_U8Cf6qJS38:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/0b26505493c78c9843fb11c49a2915add35e14c9/src/Core/Usecase/User/VerifyGoogle2fa.php#L80)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002)*

**Comment by rjmackay** [comment]
Looks good 

---

Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[application/classes/Controller/OAuth.php, line 84 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFmLPoYxRAIknJA_A:-KGUFmLPoYxRAIknJA_B:1779472088) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L84)):*
never happens..

---

*[application/classes/Controller/OAuth.php, line 90 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFfvXwTluYCIhXiAE:-KGUFfvXwTluYCIhXiAF:-1583742746) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L90)):*
This will never run..

---

*[application/classes/Controller/OAuth.php, line 95 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFh80Wy-kivcAl8P8:-KGUFh80Wy-kivcAl8P9:-1543147690) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L95)):*
I think this only happens when this is true now anywa?

---

*[application/classes/Controller/OAuth.php, line 104 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFXoHU8w_MSDVIK_E:-KGUFXoIS1cBFOKIHVjA:-438956670) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L104)):*
Do we even need the `if` here? We never return false, because we throw exceptions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002#-:-KGUGA2CcHmTUYtLQJ5r:-1921560750)*

**Comment by willdoran** [comment]
Review status: 18 of 21 files reviewed at latest revision, 7 unresolved discussions.

---

*[application/classes/Controller/OAuth.php, line 84 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFmLPoYxRAIknJA_A:-KGxthcAZZX9n5BoBCGu:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L84)):*
Done.

---

*[application/classes/Controller/OAuth.php, line 90 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFfvXwTluYCIhXiAE:-KGxtiWNoHN38z5xiIxx:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L90)):*
Done.

---

*[application/classes/Controller/OAuth.php, line 95 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFh80Wy-kivcAl8P8:-KGxtkaqKSDDm8fKnoVA:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L95)):*
Done.

---

*[application/classes/Controller/OAuth.php, line 104 \[r5\]](https://reviewable.io:443/reviews/ushahidi/platform/1002#-KGUFXoHU8w_MSDVIK_E:-KGxu1BSnNhCBUyypZWQ:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/820f41e418c512b30ba7cf8246e668797e240d97/application/classes/Controller/OAuth.php#L104)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1002)*

**Pull request closed without merging**
