### PR TITLE
Fix travis CI

### PR DESCRIPTION
**Pull request by individual-it**
This pull request makes the following changes:
- fixes the travis yml file
- fixes code-style to make lint pass

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by individual-it** [comment]
[clabot:check]

**Comment by individual-it** [comment]
you seem have disabled building on PRs in travis but in GitHub that status is still required

image

This changes should pass, see: https://github.com/individual-it/platform/pull/2 & https://travis-ci.com/individual-it/platform/builds/152124647

**Comment by tuxpiper** [comment]
> you seem have disabled building on PRs in travis but in GitHub that status is still required
> 
> image
> 
> This changes should pass, see: [individual-it#2](https://github.com/individual-it/platform/pull/2) & https://travis-ci.com/individual-it/platform/builds/152124647

Enabled  it since we no longer have useful credentials here :+1: and yes, it passes. Thanks!

**Comment by tuxpiper** [comment]
@all-contributors please add @individual-it for infra

**Pull request merged**
