### PR TITLE
Recursive diff should do a strict comparison to account for bool/truthy vals like 1 not going as true

### PR DESCRIPTION
**Pull request by rowasc**
This pull request makes the following changes:
- Fixes issue with some config features not being set because the  value would compare as true and return that nothing changed when changing ints/strings that had a default value of true in the site config. 

Test checklist:
- [ ] Test https://github.com/ushahidi/platform-cloud-interface/issues/389
- [ ] Need to add some kind of test suite to verify this didn't break half the app updates/creates of entities

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
Hold merging until we decide when this goes live

**Comment by rowasc** [comment]
I think this could get merged now that pricing is live, I could test it next week in sad-charlie and deploy it (doing a lot of other higher priority things this week )

**Comment by rowasc** [comment]
This is still very relevant. I think it should be tested and merged after the next release is live.

**Comment by tuxpiper** [comment]
> This is still very relevant as a general fix. I think it should be tested and merged after the next release is live.

Shall we label it to signify it's planned to land on the release after next?

**Comment by rowasc** [comment]
good idea yea

**Comment by rowasc** [comment]
Keeping in our notion list for reference so we can bring it up to the current code soon, closing since we don't have a plan to go live with it YET https://www.notion.so/ushahidiorg/2019-12-09-Release-replica-setup-0d35a8a7154c4de5bc69bed183c74898?p=99331d4902914a24b965c97e9d1d9528&showMoveTo=true

**Pull request closed without merging**
