### PR TITLE
Remove username from User Entity, use email address instead

### PR DESCRIPTION
**Pull request by rjmackay**
[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/704)

### CODE REVIEW

**Comment by rjmackay** [comment]
@will @jasonmule anything major you can see going wrong with this?

**Comment by will** [comment]
It's been like 15 years since I've used php, but seems reasonable.  As long as arrays can have trailing commas like that.

**Comment by rjmackay** [comment]
hah. Sorry.. @willdoran give this a review?

**Comment by jasonmule** [comment]
Looks thorough. I don't see any major issue happening because of this.

**Comment by willdoran** [comment]
Looks good, it works for me too.

**Pull request merged**
