### PR TITLE
Add documentation for installing the queue

### PR DESCRIPTION
**Pull request by rjmackay**
Add docs for running queues

### CODE REVIEW

**Comment by rjmackay** [comment]
Ugh. Something is weird with the line endings. Github's editor compained

**Comment by tuxpiper** [comment]
The changes proposed by the PR would prevail. Let's hold on until we know when we will release the associated code before merging it. That way we make sure the gitbook will not be talking about unreleased stuff.

**Comment by willdoran** [comment]
@tuxpiper This is in now right?

**Comment by rowasc** [comment]
@tuxpiper could this be merged? or are we still on hold?

**Comment by tuxpiper** [comment]
@rowasc hmmm.. this has been hanging around for so long, that it looks like it's a matter of doing a manual merge (copy / paste added content), via GitBook

**Comment by tuxpiper** [comment]
Ah, and still, looking back at my comments, we didn't release the changes ... so we will have to make sure we've got master and "version 4.0" gitbooks.. and route visitors appropriately to each

**Comment by tuxpiper** [comment]
This has been ported over to gitbooks directly , can close :+1:

**Pull request closed without merging**
