### PR TITLE
test support on PHP 7.1, 7.2 and 7.3

### PR DESCRIPTION
**Pull request by tuxpiper**
This pull request makes the following changes:
- Runs codeship tests in parallel across the currently security supported php versions

Test checklist:
- [ ] Run `jet steps` on a docker enabled hosts with codeship `jet` util installed

- [x] I certify that I ran my checklist

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
I can confirm that I can run php7.3 apparently because I've been testing with it since yesterday 🎉

**Comment by tuxpiper** [comment]
> I can't test it with jet locally today

Is this because of some friction? Anything I can help with? I think it's pretty useful to be able to replicate the CI tests locally.

**Comment by rowasc** [comment]
Thanks David ! I was able to run it.. it was all green until the end when it yelled at me because I was missing the AES key for the project. Should I grab the same key we have from  Codeship or ... somewhere  else? I didn't see one in last pass. 

(step: parallel_Deployment_director) error building container configuration: (step: parallel_Deployment_director) error parsing environment: Your Project's AES key is missing, please download from Project Settings

**Comment by tuxpiper** [comment]
Ah yep. Let me send you some details about that.

**Pull request merged**
