### PR TITLE
Fix validation issue on post create and update

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
-

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
@webong @tuxpiper can we get this into an environment and assigned to @Obadha2

**Comment by tuxpiper** [comment]
> @webong @tuxpiper can we get this into an environment and assigned to @Obadha2

with platform-client branch = develop , correct @rowasc  ?

**Comment by tuxpiper** [comment]
@Obadha2  deployed on https://pr3991.staging.ush.zone , with support user credentials as in Lastpass

**Comment by tuxpiper** [comment]
@rowasc  @webong  could you please let us know what is the issue that this fixes?

We need a description of what to test for doing the QA

**Comment by tuxpiper** [comment]
Tested and definitely an improvement :+1:

It's still possible to post something without setting the `form_id` , which I'm not sure if it's something that should be allowed. There seems to be some graceful handling on the client by later allowing the end user to assign the post to the form... but I could still do some very wacky stuff like creating posts with attributes belonging to different forms. That case would cause an unrecoverable error for the user on the client.

Anyway, one issue at a time

**Comment by tuxpiper** [comment]
This fixes #3543 , supersedes PRs #3811 #3914

**Pull request merged**
