### PR TITLE
1005 csv export

### PR DESCRIPTION
**Pull request by jasonmule**
This pull request makes the following changes:
- Allows a user to export posts from a search throught the API

Test these changes by:
- bin/behat --tags csvexport

Fixes ushahidi/platform#1005 .

Ping @ushahidi/platform

---
This change is [Reviewable](https://reviewable.io/reviews/ushahidi/platform/1033)

### CODE REVIEW

**Comment by rjmackay** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[application/classes/Controller/Api/Posts/Export.php, line 23 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwKNuyChT0-onFWy1:-KGJwKNuyChT0-onFWy2:1310785242) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L23)):*
probably override `_action_map` to block PUT, POST, DELETE requests...

also need to block action_get_index() ..

---

*[application/classes/Controller/Api/Posts/Export.php, line 34 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwUnrcipmdwFIPTWi:-KGJwUnrcipmdwFIPTWj:1346968683) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L34)):*
whats the `$format !== csv` check for? 

---

*[application/classes/Ushahidi/Formatter/Post/CSV.php, line 92 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGK22j8e4PJpNLxzmC1:-KGK22j8e4PJpNLxzmC2:-697547324) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Ushahidi/Formatter/Post/CSV.php#L92)):*
my memory of fputcsv (and other built in php CSV functions) is that they do some very stupid things (ie. don't escape properly/at all). I think we should use league CSV unless theres a reason not to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1033)*

**Comment by rjmackay** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[application/classes/Ushahidi/Formatter/Post/CSV.php, line 92 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGK22j8e4PJpNLxzmC1:-KGK3SQB2xYTbkYnSe-z:1360339979) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Ushahidi/Formatter/Post/CSV.php#L92)):*
Actually I take that back.. the docs look like it does OK. Maybe I'm remembering the CSV import functions. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1033)*

**Comment by jasonmule** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[application/classes/Controller/Api/Posts/Export.php, line 34 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwUnrcipmdwFIPTWi:-KGkPbZUnarO3-AoD71-:-527828308) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L34)):*
Was going to use this for other export types but it's not needed at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1033)*

**Comment by rjmackay** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[application/classes/Controller/Api/Posts/Export.php, line 34 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwUnrcipmdwFIPTWi:-KGnax9C0cRFthzJSa6Q:2058557512) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L34)):*
Right.. my confusion was why not just check `if ($format)` and as long as formatter.entity.post.csv exists it'll be fine?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1033)*

**Comment by jasonmule** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[application/classes/Controller/Api/Posts/Export.php, line 23 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwKNuyChT0-onFWy1:-KGr-DUkdSc24g1qp8Db:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L23)):*
Done.

---

*[application/classes/Controller/Api/Posts/Export.php, line 34 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/1033#-KGJwUnrcipmdwFIPTWi:-KGqzbqeCqqfrhNf1ums:-1530771663) ([raw file](https://github.com/ushahidi/platform/blob/70f87b1d55b6d8a50e0ca25469759ee2f1fd3141/application/classes/Controller/Api/Posts/Export.php#L34)):*
Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ushahidi/platform/1033)*

**Pull request closed without merging**
