### PR TITLE
feat(users): Disable registration

### PR DESCRIPTION
**Pull request by SaifurRahmanMohsin**
This pull request makes the following changes:
- Adds a **disable registration** feature.
- When enabled, blocks new user registration at the API level .
- Implemented [as per this approach](https://github.com/ushahidi/platform/issues/3918#issue-596600107).

Test checklist:
- [x] Ensure that the feature is picked up by the client (this feature should exist in the response of the features API endpoint).
- [x] When the feature is enabled and also the disable registration is turned ON (off by default), ensure that requests to the register API lead to a 403 exception.

- [x] I certify that I ran my checklist

Fixes ushahidi/platform#3918.

Ping @ushahidi/platform

### CODE REVIEW

**Review by rowasc — CHANGES_REQUESTED** [review]
This is great. Looking forward to testing!
cc @Obadha2 please test when you can (you will need to merge this one and the client side PR  https://github.com/ushahidi/platform-client/pull/1602)

**Review by rowasc — CHANGES_REQUESTED** [review]
A request if you can: could you add a test for this feature in the API verifying the endpoint is open by default and closed when the feature is set as disabled? Thanks! if that's not possible let me know and we can help. For examples on how this would be tested you can check out the scenario setups in PHPUnitFixtureContext for makePrivate (for the site private configuration) and the integration tests using the `@private` in the integration tests

**Comment by SaifurRahmanMohsin** [comment]
@rowasc Thank you--I'm glad that the PR is valid and works great. I've managed to figure out how to add the feature test based on your suggestions and was able to run it using the behat tool to get a success. I hope that it is accurate and does the job well.

**Comment by SaifurRahmanMohsin** [comment]
@rowasc I'm glad to hear that the PR looks great. I was able to figure out how to add the feature test based on your suggestions/tips and was able to run it using the behat tool to get the success messages as expected. I hope it's all good and can be merged. Thank you.

**Comment by SaifurRahmanMohsin** [comment]
Hello @rowasc. I hope you were able to check out the changes I made? If not could you kindly verify and merge if so? Or please let me know if something is missed out. Thanks.

**Comment by SaifurRahmanMohsin** [comment]
Hello @rowasc. I hope you were able to check out the test code that I added? If you have and all if good can we go ahead and close this? If something is missed out, kindly let me know. Thanks.

**Comment by SaifurRahmanMohsin** [comment]
Hello @rowasc. If everything looks good, can we have this merged? Or have I missed anything out?

**Review by rowasc — APPROVED** [review]
This is great. Thank you @SaifurRahmanMohsin  ! 

@Obadha2 we should be able to test this now! (check out the client side PR that has to be merged together with this one too, it's linked above)

**Comment by SaifurRahmanMohsin** [comment]
Hi @Obadha2 could you kindly review/test my PR?

**Comment by SaifurRahmanMohsin** [comment]
@Obadha2 Thanks for reviewing my PR and merging. 👍🏽

**Pull request merged**
