### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gvarisco**
Fixed 'getin' link.

[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/862)

### CODE REVIEW

**Comment by gvarisco** [comment]
[clabot:check]

**Comment by gvarisco** [comment]
Just noticed it duplicates #831 - feel free to close it.

**Comment by aoduor** [comment]
Hey @gvarisco thanks for this. Someone on our team will review your pull request and be in touch in the course of this and next week!

**Comment by willdoran** [comment]
This looks good, thanks!

**Pull request merged**
