### PR TITLE
feat(country code): add query for country code

### PR DESCRIPTION
**Pull request by kubabialy**
This pull request makes the following changes:
-

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Solves ushahidi/platform #4498 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Mh-Asmi** [comment]
you need to handle the case of there isn't a match of id in FetchCountryCodeByIdQuery

**Comment by kubabialy** [comment]
@Mh-Asmi https://github.com/ushahidi/platform/pull/4497/files#diff-fa61f90ede2480c1513b445f13cfd8cafab17af65b4eda3b5027e3bf9cb878a5R42 if you look at the tests you'll find out that this case is already covered. Unless there's something else I should know about.

**Comment by Mh-Asmi** [comment]
can you move CountryCodePolicy to V5/Policies

**Comment by Mh-Asmi** [comment]
please rename the folders inside Acstions/CountryCode 
- as we agreed - 
Query--> Queries
QueryHandler --> Handlers

**Review by Mh-Asmi — APPROVED** [review]

**Pull request merged**
