### PR TITLE
Lumen console to artisan

### PR DESCRIPTION
**Pull request by rjmackay**
This pull request makes the following changes:
- Remove old command and console application
- Move import command to artisan
- Fix up mergeing defaults into config
- Move notifications and saved search commands into artisan
- Move webhook command to artisan
- Move user:create/delete to artisan
- Move dataprovider commands to artisan
- Move config:get/set commands into artisan

Test checklist:
- [x] Run ./artisan
- [x] Run ./bin/ushahidi
- [x] Run ./artisan config:get
- [x] Run ./artisan config:set ...
- [x] Run ./artisan dataprovider:incoming
- [x] Run ./artisan dataprovider:outgoing
- [x] Run ./artisan user:create
- [x] Run ./artisan user:delete
- [x] Run ./artisan savedsearch:sync
- [x] Run ./artisan notification:queue 
- [x] Run ./artisan webhook:send
- [x] Run ./artisan export (Doesn't appear to work yet?)

Refs #1372 

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rjmackay** [comment]
@rowasc @willdoran did the post exporter CLI command work in the main branch? I'm getting no output

**Comment by rowasc** [comment]
@rjmackay Robbie, it should. :/  I exported about 50k rows last week with it.

**Comment by rjmackay** [comment]
Fixed with the latest lumen

**Comment by kinstelli** [comment]
All of the commands above are running, but are there specific inputs/outputs to be tested, e.g.:
`./artisan config:get site`
`./artisan config:get features` , 
` ./artisan  user:create --realname=someperson --email=someone@example.com`

**Pull request merged**
