### PR TITLE
README Update link: Getting Involved

### PR DESCRIPTION
**Pull request by RAbraham**
Update Link

[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/831)

### CODE REVIEW

**Comment by RAbraham** [comment]
[clabot:check]

2015-11-19 20:49 GMT-05:00 Ushbot <notifications@github.com>:

> Hey @RAbraham <https://github.com/RAbraham>,
> thank you for your Pull Request.
>
> It looks like you haven't signed our *C*ontributor *L*icense *A*greement,
> yet.
>
> The purpose of a CLA is to ensure that the guardian of a project's outputs
> has the necessary ownership or grants of rights over all contributions to
> allow them to distribute under the chosen licence.
> Wikipedia <http://en.wikipedia.org/wiki/Contributor_License_Agreement>
>
> You can read and sign our full Contributor License Agreement here.
>
> Once you've signed reply with [clabot:check] to prove it.
>
> Appreciation of efforts,
>
> clabot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/pull/831#issuecomment-158255707>.
>



-- 
Take care,
Rajiv

**Comment by RAbraham** [comment]
[clabot:check]

2015-11-19 20:51 GMT-05:00 Rajiv Abraham <rajiv.abraham@gmail.com>:

> [clabot:check]
>
> 2015-11-19 20:49 GMT-05:00 Ushbot <notifications@github.com>:
>
>> Hey @RAbraham <https://github.com/RAbraham>,
>> thank you for your Pull Request.
>>
>> It looks like you haven't signed our *C*ontributor *L*icense *A*greement,
>> yet.
>>
>> The purpose of a CLA is to ensure that the guardian of a project's
>> outputs has the necessary ownership or grants of rights over all
>> contributions to allow them to distribute under the chosen licence.
>> Wikipedia <http://en.wikipedia.org/wiki/Contributor_License_Agreement>
>>
>> You can read and sign our full Contributor License Agreement here.
>>
>> Once you've signed reply with [clabot:check] to prove it.
>>
>> Appreciation of efforts,
>>
>> clabot
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ushahidi/platform/pull/831#issuecomment-158255707>.
>>
>
>
>
> --
> Take care,
> Rajiv
>



-- 
Take care,
Rajiv

**Comment by aoduor** [comment]
Hey @RAbraham pardon our delayed action, and thanks for your pull request. Someone on our team will review your pull request and be in touch in the course of this and next week!

**Comment by rjmackay** [comment]
[clabot:check]

**Comment by rjmackay** [comment]
[clabot:check]
 Show all checks

**Comment by rjmackay** [comment]
[clabot:check]

**Comment by rjmackay** [comment]
[clabot:check]

**Pull request merged**
