### PR TITLE
Roles [Review only, already merged to develop]

### PR DESCRIPTION
**Pull request by rjmackay**
[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/903)

### CODE REVIEW

**Comment by rjmackay** [comment]
+@jasonmule I've posted a bunch of feedback and questions below

---

Reviewed 17 of 35 files at r1, 5 of 9 files at r2, 32 of 39 files at r3.
Review status: 52 of 59 files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[application/classes/Ushahidi/Repository/Post.php, line 42 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAatIDLgBgtW5APbWkY:-KAatIDOpTwHtXpMK8nm:-762663113) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/Post.php#L42)):*
Document what functions this adds please

---

*[application/classes/Ushahidi/Repository/Post.php, line 463 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAam1GN7jEWypmGFO9H:-KAam1GO9NmBwP95Sufy:1964235211) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/Post.php#L463)):*
Hardcoded Admin should disappear entirely here if possible. If we want to give admin all privs, do that in the ACL/authorizer, not repo. However this was always a little hacky so maybe you can't do that without sideeffects?

---

*[application/classes/Ushahidi/Repository/User.php, line 52 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaniTj9rRGfMBG2zpL:-KAaniTkHVAYMcPVCvN9:-1273994315) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L52)):*
Indenting fail. Mix tabs and spaces all through this file.

---

*[application/classes/Ushahidi/Repository/User.php, line 53 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaoDlAULcilrLgm6Xh:-KAaoDlAULcilrLgm6Xi:1333720084) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L53)):*
why are we pushing permissions onto the User entity? seems to create extra work later..

---

*[application/classes/Ushahidi/Repository/User.php, line 81 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAao4OtXBJxHg4XrD7Z:-KAao4OtXBJxHg4XrD7_:-600600018) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L81)):*
Why aren't we handing off to parent::create() any more?

---

*[application/tests/datasets/ushahidi/Base.yml, line 3 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaocdVdSk9Yqu0YFHl:-KAaocdVdSk9Yqu0YFHm:-1087483375) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/tests/datasets/ushahidi/Base.yml#L3)):*
Why are we now capitalizing these? That kind defeats the purpose of display name.. and I expect will break a few things on upgrade. Especially since we don't have migration to change the roles already in the DB.

---

*[composer.lock, line 151 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaowPoRDIWF8EKw-6y:-KAaowPpVmBZAVWU1mr7:893272230) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/composer.lock#L151)):*
merge junk. Please fix

---

*[src/Core/Entity/Config.php, line 21 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAapf30XQnNjxwhrP3n:-KAapf30XQnNjxwhrP3o:-524788201) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Entity/Config.php#L21)):*
Why are we adding this to the Entity directly? I don't think Authorization/Access control shouldn't really exist on the core entity, rather it belongs in the Authorizers.

---

*[src/Core/Entity/User.php, line 34 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaptMea28B7O7q8nb7:-KAaptMea28B7O7q8nb8:-2071665608) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Entity/User.php#L34)):*
repeating myself - but why does this need to be here? .. OK if its necessary right now but we're kinda fudging our domain models, so we should add a tech-debt task + comment to clean these up

---

*[src/Core/Tool/Authorizer/ConfigAuthorizer.php, line 65 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaqEd3_SYz1EpN4Bo3:-KAaqEd3_SYz1EpN4Bo4:-98831556) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Tool/Authorizer/ConfigAuthorizer.php#L65)):*
when would the entity ever NOT be Permissionable? Seems to me this should just be assumed and the interface can throw an error if not.

---

*[src/Core/Tool/Permissions/Acl.php, line 25 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaqtIvLBm8FXzJz0a8:-KAaqtIvLBm8FXzJz0a9:-1457086048) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Tool/Permissions/Acl.php#L25)):*
Why is permissions an array, we only ever check a single permission?

---

*[src/Core/Tool/Permissions/Permissionable.php, line 21 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAar1E5l3FuPHcLQCQG:-KAar1E5l3FuPHcLQCQH:-1658056270) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Tool/Permissions/Permissionable.php#L21)):*
We only ever use a single permission - I'd be tempted to just make this return a string.

---

*[src/Core/Traits/PermissionAccess.php, line 46 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAarRMoqvjl-1T5OaXy:-KAarRMoqvjl-1T5OaXz:1723988069) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Traits/PermissionAccess.php#L46)):*
I'm not sure the roles feature flag should disable the ACL check itself..

We should either just run the same checks - which leaves us having to update permissions if a user downgrades plans. Or fallback to default permissions/roles (ie. ignore the DB)...
maybe this achieves that and I'm just missing it?? ie. this returns false, do we have other default permission in the authorizers anyway??

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903#-:-KAassvsi7-sVd0Xob6h:-1845185192)*

**Comment by jasonmule** [comment]
*[application/classes/Ushahidi/Repository/User.php, line 53 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaoDlAULcilrLgm6Xh:-KAazx04g4d1B7Hx_lh6:-2080057467) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L53)):*
@Will Sorry I forgot to review when I merged this. Are we still relying on the user entity having permissions on the client?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by willdoran** [comment]
Yep, we need it to check the auth stuff for general users.

**Comment by willdoran** [comment]
Yeah, so display_name and name are an issue. We do need to irradicate the existence of both.

**Comment by jasonmule** [comment]
*[src/Core/Traits/PermissionAccess.php, line 46 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAarRMoqvjl-1T5OaXy:-KAb7nEef_aA-9UiyLXE:1090334464) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Traits/PermissionAccess.php#L46)):*
So, if the user downgrades plans, the permissions check in the authorizer has no effect and the default permissions in the authorizers are in effect i.e. check Admin and move on to checking privileges as usual.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by rjmackay** [comment]
> Yeah, so display_name and name are an issue. We do need to irradicate the existence of both.
I don't understand this? whats the problem with these? `name` originally was a unique ID, while display name was intended to be editable

**Comment by jasonmule** [comment]
*[application/classes/Ushahidi/Repository/Post.php, line 463 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAam1GN7jEWypmGFO9H:-KAeAM3eOJpw3XbtFIF8:-1947929334) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/Post.php#L463)):*
Looks like this is a bit tricky here since query filters depend on access at the moment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by jasonmule** [comment]
Review status: 26 of 52 files reviewed at latest revision, 13 unresolved discussions.

---

*[application/classes/Ushahidi/Repository/User.php, line 52 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaniTj9rRGfMBG2zpL:-KAeAg5qfQED5-wM8Mrw:984129001) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L52)):*
Reverting this...

---

*[application/classes/Ushahidi/Repository/User.php, line 81 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAao4OtXBJxHg4XrD7Z:-KAeAmfrognnnHmNNeCF:-211555499) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L81)):*
Reverting.

---

*[src/Core/Entity/User.php, line 34 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaptMea28B7O7q8nb7:-KAeAuj2JgX8ZMxArJ6O:1517196281) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Entity/User.php#L34)):*
Reverting

---

*[src/Core/Tool/Authorizer/ConfigAuthorizer.php, line 65 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaqEd3_SYz1EpN4Bo3:-KAeAwrl0F5XN0L1D0vP:392271611) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Tool/Authorizer/ConfigAuthorizer.php#L65)):*
Moved permissions to authorizers.

---

*[src/Core/Entity/Config.php, line 21 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAapf30XQnNjxwhrP3n:-KAeB3M-r5U79cK2yyh3:392271611) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Entity/Config.php#L21)):*
Moved permissions to authorizers.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by jasonmule** [comment]
@rjmackay Merged changes to `develop`. Leaving this here for review.

**Comment by rjmackay** [comment]
Nice work thanks. Couple of minor comments still but low priority

---

Review status: 26 of 52 files reviewed at latest revision, 8 unresolved discussions.

---

*[application/classes/Ushahidi/Repository/User.php, line 53 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaoDlAULcilrLgm6Xh:-KAl0R0mnzsveSnLo1IY:-2110178222) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L53)):*
Ok.. not ideal but makes sense for now.

---

*[src/Core/Entity/User.php, line 34 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaptMea28B7O7q8nb7:-KAl1AAifrrHAQdxmQdQ:-1981584581) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Entity/User.php#L34)):*
huh? but you still have permissions in the object?

---

*[src/Core/Tool/Authorizer/ConfigAuthorizer.php, line 65 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaqEd3_SYz1EpN4Bo3:-KAl1O3kDJj6PC5C43dd:-725550802) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/src/Core/Tool/Authorizer/ConfigAuthorizer.php#L65)):*
:boom: Nice work

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903#-:-KAl1nrMXCe_3i3P8ZU2:774398291)*

**Comment by rjmackay** [comment]
Reviewed 1 of 35 files at r1, 2 of 9 files at r2, 2 of 39 files at r3, 23 of 29 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/Core/Entity/Post.php, line 21 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAl2xH8ad4mijLS9IZ2:-KAl2xH8ad4mijLS9IZ3:-1845037176) ([raw file](https://github.com/ushahidi/platform/blob/d5d717e33c50e1720103409df3bb3e85e6eae414/src/Core/Entity/Post.php#L21)):*
Can we remove the Permissionable traits from all the entities please?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by jasonmule** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[application/classes/Ushahidi/Repository/User.php, line 53 \[r3\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAaoDlAULcilrLgm6Xh:-KAlCiO8esmDXDYLe8Jx:1540205755) ([raw file](https://github.com/ushahidi/platform/blob/354f90a5086bf6b8760977d9af0002a0b279afc4/application/classes/Ushahidi/Repository/User.php#L53)):*
Reverted to getting permissions from `Role`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by rjmackay** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[migrations/20160215185411_add_roles_permissions.php, line 23 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAlIkhrGZWTbhEQCRhB:-KAlIkhs-9cjfmkEOG-T:1131559118) ([raw file](https://github.com/ushahidi/platform/blob/d5d717e33c50e1720103409df3bb3e85e6eae414/migrations/20160215185411_add_roles_permissions.php#L23)):*
I think this has potential to be problematic: we're using permissions.name as both a display name and the permission ID..

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by jasonmule** [comment]
*[migrations/20160215185411_add_roles_permissions.php, line 23 \[r4\]](https://reviewable.io:443/reviews/ushahidi/platform/903#-KAlIkhrGZWTbhEQCRhB:-KAlJnltzTEKLRS-qKqC:1982966449) ([raw file](https://github.com/ushahidi/platform/blob/d5d717e33c50e1720103409df3bb3e85e6eae414/migrations/20160215185411_add_roles_permissions.php#L23)):*
Permissions are readonly at the moment but we should add a display name eventually...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/903)*

**Comment by rjmackay** [comment]
Closing .. Nice work.

**Pull request closed without merging**
