### PR TITLE
Release last transifex updates

### PR DESCRIPTION
**Pull request by rowasc**
This pull request makes the following changes:
-

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
@Obadha2 this is ready to merge (it's an automatic code update basically from transifex, as part of the release) . Can't self-approve it so tagging you instead to merge it when you are ready .

**Comment by Obadha2** [comment]
Hmm on my end, I see this requires an approving review @rowasc

**Comment by rowasc** [comment]
>Hmm on my end, I see this requires an approving review @rowasc
Yep. Is it ok if I merge it? - I don't need approval here, I just need to coordinate with you -

**Comment by Obadha2** [comment]
Yes yes, it's okay. 👍 
Thanks!

**Pull request merged**
