### PR TITLE
Merge/2023.42

### PR DESCRIPTION
**Pull request by tuxpiper**
This pull request makes the following changes:
- Brings in hot fixes from release/2023.42

### CODE REVIEW

**Comment by tuxpiper** [comment]
@webong please check urgently.

Are these the changes that you've been doing on the latest release branch that had not been brought to develop yet?

**Comment by webong** [comment]
> @webong please check urgently.
> 
> Are these the changes that you've been doing on the latest release branch that had not been brought to develop yet?

Yes, they haven't been brought to develop. This is good to go!  @tuxpiper

**Comment by tuxpiper** [comment]
GIve your ap

> > @webong please check urgently.
> > Are these the changes that you've been doing on the latest release branch that had not been brought to develop yet?
> 
> Yes, they haven't been brought to develop. This is good to go! @tuxpiper

Ok :) Give your approval flag please?

**Review by webong — APPROVED** [review]
Ready to merge!

**Comment by Mh-Asmi** [comment]
I will merge it, to start working on urgent issues

**Pull request merged**
