### PR TITLE
Add superpowers flag to give some oauth clients access to set config

### PR DESCRIPTION
**Pull request by rjmackay**
Allows an oauth client to set config without a user session. The usecase is allowing our cloud management jobs to push config to deployments.

[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/707)

### CODE REVIEW

**Comment by rjmackay** [comment]
@willdoran @jasonmule Can you give this a review?
I've rushed a bit with this.. hopefully your first thought isn't "whoa thats a bad idea".. but if it is I want to know :)

**Comment by jasonmule** [comment]
Not really comfortable about having an admin and a super powered user with a back door on the same platform..

**Comment by rjmackay** [comment]
So to clarify this doesn't add a 'superpower' user. Its a super powered oauth client. ie. no user login, just oauth client + secret.
I debated the naming a little.. the permissions are slightly different: 
- Superpowered client can change any config setting, including which features are enabled (used to power tiers in cloud)
- Admins can only edit site and data provider config..

.. you do make a good point though. Its feels like this is asking for confusion later.  Any thoughts on a better permissions model? or just better naming?

Some of it might get cleared up when we build custom roles, since we could split things out into 'permissions'.. but need a good solution now too.

**Comment by jasonmule** [comment]
Understood. Maybe call it config manager since we are using it to only change configs? :-)

**Comment by rjmackay** [comment]
That definitely a more useful description. The scope might expand later. ie. I can imagine giving access to modify users in future. Maybe `deployment manager` or just `manager`.. but that sounds too much like `admin` again.

The other option, is to avoid this entirely and set config through a CLI task ie. `bin/ushahidi config:set` .. I started down that road but got stuck.

**Comment by rjmackay** [comment]
While we figure this out.. heres a PR for setting config via the console instead https://github.com/ushahidi/platform/pull/709

**Comment by rjmackay** [comment]
Closing this PR (but leaving the branch). We can re-add later if needed

**Pull request closed without merging**
