### PR TITLE
initial commit for adding FB messenger Bot

### PR DESCRIPTION
**Pull request by rohit645**
This pull request makes the following changes:
-Initial configuration for a Facebook Messenger Bot. 

Feature addition in reference to ushahidi/platform#3686 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by rowasc** [comment]
@rohit645 thanks for your initial config PR. As early feedback: can you feature flag this so that we have the ability to do soft launches safely once the FB Bot is integrated?

**Comment by rohit645** [comment]
> @rohit645 thanks for your initial config PR. As early feedback: can you feature flag this so that we have the ability to do soft launches safely once the FB Bot is integrated?

@rowasc Sorry, I didn't get what you wanted to say. Can you please elaborate? I don't have idea of how feature flag works?

**Comment by rowasc** [comment]
@rohit645 sorry, my bad I should have expanded! 
So we use feature flags when we want to have the ability to deploy without releasing a feature. What I mean by this is that for instance, we could eventually merge the FB Bot code under a "disabled" state that only those who want it would change to enabled. 
To check if a feature is enabled, you can use something like:
`Features::isEnabled('fbbot')`  
before enabling the routes etc. 

Example we used to enable HXL (for HDX ) just for one deployment (HDX integration is the last "big" feature we released after a period of it existing but being only available for select deployments ) . 

`Features::isEnabled('hxl')` would give you the state of enabled/disabled of the HXL feature for instance. 
In the route you could add `feature:hxl` (or `feature:fbbot` )  as the middleware as well, in order to enable or disable the FBBot's routes on demand. 

and then in the client you'd check with something like ` !Features.isFeatureEnabled('hxl')`  if you wanted to show a part of the UI conditionally (just an example). 

Not sure if this helps at all. I should probably write a better guide. I can invest a bit more on this type of doc closer to end of week if that'd help since it's not documented

**Comment by rowasc** [comment]
been thinking about this
@tuxpiper it's not clear to me that we will want to merge this *into* platform itself. I would prefer a chatbot as a separate repository, with the code here only being related to actually connecting the thing, much like Anna's bot was separate and like Tim's USSD setup (even better), because it alligns much better with our vision for the future as interconnected services. Thoughts?

**Comment by tuxpiper** [comment]
> been thinking about this
> @tuxpiper it's not clear to me that we will want to merge this _into_ platform itself. I would prefer a chatbot as a separate repository, with the code here only being related to actually connecting the thing, much like Anna's bot was separate and like Tim's USSD setup (even better), because it alligns much better with our vision for the future as interconnected services. Thoughts?

agreed, I also think it would be much better in terms of architecture :+1:

**Pull request closed without merging**
