### PR TITLE
WIP: Update Platform Docs

### LINKED ISSUE #3514: Streamline and document local docker-compose setup for developers
Aha! Link: https://ushahiditeam.aha.io/features/PROD-231

### PR DESCRIPTION
**Pull request by Timtech4u**
This pull request makes the following changes:
- Updates the deployment instructions on the project docs

WIP: Intends to Fix #3514 .

Ping @timtech4u

### CODE REVIEW

**Comment by Timtech4u** [comment]
[clabot:check]

**Comment by Timtech4u** [comment]
[clabot:check]

**Comment by rowasc** [comment]
[clabot:check]

**Comment by rowasc** [comment]
Thanks Tim. Closing since we have moved the docs to the devhub now. Thanks

**Pull request closed without merging**
