### PR TITLE
fix: user permission is now checked for api key authorizer

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
- Adds ACL Manager Settings permission check on users
References https://github.com/ushahidi/platform/issues/3261 
Test checklist:
With an administrator user
- [ ] Create a role with the Manage Settings permission only
- [ ] Assign the role to a user
With a user who has the new role assigned
- [ ] login with that user, access the settings page (you should see this page instead of access denied)
- [ ] access the general settings
- [ ] change a general setting -  site name and regenerate API keys
- [ ] save
- [ ] the settings should save
- [ ] log out
- [ ] the site name should change to what you assigned to it (check the browser tab and the map view)
- [ ] You can check the API key changed in the database, too, or simply reload the settings admin page to see it

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by Angamanga** [comment]
@rowasc @tuxpiper Could one of you review please?

**Comment by rowasc** [comment]
Reviewing and testing @Angamanga

**Comment by rowasc** [comment]
@webong this looks good and seems to work just fine, thank you so much 🎉 
Just an extra request, if you're willing:  would you be able to add an integration test for it? 
Roughly would involve
- creating a new role with the "Manage Settings" permission in tests/datasets/ushahidi/Base.yml
- create a user specifically for this role in the same file (users key)
- assign the user with that role in the same file (roles_permissions key in Base.yml)
- checking that the user has access to apikeys  and other general settings (the acl.feature file may offer some guidance on this workflow)
The api.apikeys.feature file in the integration tests may be another place to add a role/permission check if you'd like too. \

**Comment by webong** [comment]
@rowasc thanks for the review ... my latest push now implements an integration test.

**Comment by Angamanga** [comment]
@rowasc is this one ok to merge now?

**Comment by rowasc** [comment]
yes!

**Pull request merged**
