### PR TITLE
Modified DataSource Storage to Log Errors 

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
-

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Related to: ushahidi/platform#4066 .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by webong** [comment]
@tuxpiper this is the PR from last week.

**Comment by tuxpiper** [comment]
@webong could you please base these changes off develop ? It would be great if we included this in the next regular release of Platform

**Comment by webong** [comment]
Okay ... I'll try that out. To do this, I'll need to use the git rebase command right.

**Comment by tuxpiper** [comment]
> Okay ... I'll try that out. To do this, I'll need to use the git rebase command right.

Yea :) see https://git-scm.com/book/en/v2/Git-Branching-Rebasing  under "More Interesting Rebases"

**Comment by webong** [comment]
@tuxpiper can you help rebasing this to develop ... thank you.

**Comment by tuxpiper** [comment]
Closing in favor of #4068

**Pull request closed without merging**
