### PR TITLE
Use lat, lon mappings to extract a location point

### PR DESCRIPTION
**Pull request by jasonmule**
[Review on Reviewable](https://reviewable.io/reviews/ushahidi/platform/943)

### CODE REVIEW

**Comment by rjmackay** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[application/classes/Ushahidi/Transformer/CSVPostTransformer.php, line 101 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/943#-KAnnFUtfikjwA1p-pGT:-KAnnFUuVOsbD4HYpwiB:-1809478146) ([raw file](https://github.com/ushahidi/platform/blob/dad8ea603f6d9b2458edb857dca00ad06c49df73/application/classes/Ushahidi/Transformer/CSVPostTransformer.php#L101)):*
Can we do a more exact match? ie. check for ending with ".lat" not just containing lat

In future we should do a generic solution to just explode dot-notation but not day before launch :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/943)*

**Comment by jasonmule** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[application/classes/Ushahidi/Transformer/CSVPostTransformer.php, line 101 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/943#-KAnnFUtfikjwA1p-pGT:-KAnu6ipXCqvzOZilqFh:-499146009) ([raw file](https://github.com/ushahidi/platform/blob/dad8ea603f6d9b2458edb857dca00ad06c49df73/application/classes/Ushahidi/Transformer/CSVPostTransformer.php#L101)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/943)*

**Comment by rjmackay** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[application/classes/Ushahidi/Transformer/CSVPostTransformer.php, line 101 \[r1\]](https://reviewable.io:443/reviews/ushahidi/platform/943#-KAnnFUtfikjwA1p-pGT:-KAnuDr3IhDObwUjM3xf:1618420197) ([raw file](https://github.com/ushahidi/platform/blob/dad8ea603f6d9b2458edb857dca00ad06c49df73/application/classes/Ushahidi/Transformer/CSVPostTransformer.php#L101)):*
I think its important to match the "." otherwise any field name that ends in 'lat' will match right?

---

*[application/classes/Ushahidi/Transformer/CSVPostTransformer.php, line 118 \[r2\]](https://reviewable.io:443/reviews/ushahidi/platform/943#-KAnuUpdA4f649wnOVw5:-KAnuUpdA4f649wnOVw6:2039089406) ([raw file](https://github.com/ushahidi/platform/blob/2ab732ad540a88e872b3a99b4f6ac30f65d25cbf/application/classes/Ushahidi/Transformer/CSVPostTransformer.php#L118)):*
This fails if we have more than one location field..

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/943)*

**Comment by rjmackay** [comment]
Ship it :)

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/ushahidi/platform/943#-:-KAo8QC6Hw1wb1lPDKU9:392912453)*

**Pull request merged**
