### PR TITLE
fix: auto detect the encoding of string during conversion

### PR DESCRIPTION
**Pull request by webong**
This pull request makes the following changes:
- Adds an auto detect to the mb_convert_encoding

Test checklist:
- [ ]

Fixes USH_823 for Pre-Mzima .

Ping @ushahidi/platform

### CODE REVIEW

**Comment by webong** [comment]
@tuxpiper does this issue go into production build for pre-mzima (legacy) if merged into this branch?

**Comment by tuxpiper** [comment]
> @tuxpiper does this issue go into production build for pre-mzima (legacy) if merged into this branch?

Yes, this is the right branch. It won't deploy automatically, though. We will need to do a manual deployment.

Is the same fix already in mzima?

**Comment by webong** [comment]
> > @tuxpiper does this issue go into production build for pre-mzima (legacy) if merged into this branch?
> 
> Yes, this is the right branch. It won't deploy automatically, though. We will need to do a manual deployment.
> 
> Is the same fix already in mzima?

Yes I made a corresponding PR to the current development branch too

**Comment by tuxpiper** [comment]
@webong this is deployed now

**Pull request merged**
