### PR TITLE
Test documentation  Development installation with XAMPP #3662

### PR DESCRIPTION
**Pull request by muchirijane**
This pull request makes the following changes:
- In the documentation configuring the API section, Change the DB_USER to root in the `.env` file there is DB_USERNAME listed instead. That's what I changed. Maybe that section could be updated in the documentation. 
- When running `composer migrate` I got an error

composer migrate

> php artisan environment:verify
Running OAuth key checks
Good job! Your OAuth keys are in the right place.
We will check the environment file next.
Running ENV configuration checks
DB_PASSWORD is missing in the environment or .env file.
Please set the password to connect to your database in the DB_PASSWORD key
Running DB connectivity verification
We were able to connect to the DB. Well done!

`In EnvironmentVerify.php line 84:
Verification Failed.
Script PHP artisan environment: verify handling the verify event returned with error code 1
Script @verify was called via migrate `

- Configure the platform/.htaccess file - I could not see this file, I created a .htaccess myself and copied the code in the documentation.
- Got stuck at this section : Windows: In the XAMPP control panel, click the "Config" button next to Apache and select "Apache (httpd.conf)". This will open an editor with the file. In my case, I thought it was checking the [ ] Apache but an editor didn't open.

 xampp screenshot error

- Suggestions - The last part can be a bit complex for someone who is a beginner in contribution. It would be helpful if the last part of the documentation could be turned into a video. The videos are really helpful especially since it's visual and you easily follow through the steps.
- Overall the documentation is clear and the videos are even more helpful.

Test checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

Aha! Link: https://ushahiditeam.aha.io/features/PROD-846

### CODE REVIEW

**Comment by muchirijane** [comment]
[clabot:check]

**Comment by rowasc** [comment]
hey @muchirijane I'm not sure if I understand correctly, you mention
>In the documentation configuring the API section, Change the DB_USER to root in the .env file there is DB_USERNAME listed instead. *That's what I changed.* Maybe that section could be updated in the documentation.
but this doesn't really include a change on defaults to the docs

**Comment by muchirijane** [comment]
Hey, @rowasc I was saying in the official doc (https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/xampp). Changes should be done in the DB_USER but I really couldn't see it, I thought the docs meant DB_USERNAME. But since it's something small, maybe updating the change won't be necessary. 👍🏽

**Comment by rowasc** [comment]
@muchirijane oh, please  change it in the doc then :) even  small things can have a big impact if they remove confusion

**Comment by muchirijane** [comment]
Hey @rowasc, please would you guide through how to change your documentation. I don't know the front-end code of the documentation.

**Pull request closed without merging**
